LINEAR DATA - HOUSE PRICE PREDICTION

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,root_mean_squared_error,mean_absolute_error,r2_score

In [ ]:
df=pd.read_csv("house_prices.csv")

In [ ]:
df

,Area Sq Ft,Bedrooms,Bathrooms,House Age Years,Distance to City Km,House Price
0,1324,4,3,8,17.4,211126.13
1,2529,2,1,13,14.6,311095.05
2,1759,3,4,39,8.5,236850.76
3,1409,3,3,8,11.3,220737.54
4,2102,3,4,19,4.3,305919.72
...,...,...,...,...,...,...
95,556,4,2,27,15.4,98602.88
96,737,3,4,18,3.5,144911.52
97,2707,4,2,12,8.6,361088.80
98,1699,1,1,33,20.7,180261.12
99,2009,2,3,28,11.2,258353.96

In [ ]:
df.corr()

,Area Sq Ft,Bedrooms,Bathrooms,House Age Years,Distance to City Km,House Price
Area Sq Ft,1.000000,-0.022038,-0.044407,-0.006335,0.057610,0.959858
Bedrooms,-0.022038,1.000000,-0.042408,-0.122020,-0.045001,0.137946
Bathrooms,-0.044407,-0.042408,1.000000,-0.053686,-0.001282,0.055101
House Age Years,-0.006335,-0.122020,-0.053686,1.000000,0.029517,-0.170619
Distance to City Km,0.057610,-0.045001,-0.001282,0.029517,1.000000,-0.091559
House Price,0.959858,0.137946,0.055101,-0.170619,-0.091559,1.000000

CONCLUSION  --->  
1. Area Sq Ft has a very strong positive correlation (0.959858) with House Price.
2. Bedrooms and Bathrooms have weak positive correlations, while House Age and Distance to City have weak negative correlations with House Price.
3. Therefore, Area Sq Ft is the most strongly linearly associated feature with House Price in this dataset.

In [ ]:
x=df.drop(columns='House Price')
y=df['House Price']

In [ ]:
x

    Area Sq Ft  Bedrooms  Bathrooms  House Age Years  Distance to City Km
0         1324         4          3                8                 17.4
1         2529         2          1               13                 14.6
2         1759         3          4               39                  8.5
3         1409         3          3                8                 11.3
4         2102         3          4               19                  4.3
..         ...       ...        ...              ...                  ...
95         556         4          2               27                 15.4
96         737         3          4               18                  3.5
97        2707         4          2               12                  8.6
98        1699         1          1               33                 20.7
99        2009         2          3               28                 11.2

[100 rows x 5 columns]

In [ ]:
y

0     211126.13
1     311095.05
2     236850.76
3     220737.54
4     305919.72
        ...
95     98602.88
96    144911.52
97    361088.80
98    180261.12
99    258353.96
Name: House Price, Length: 100, dtype: float64

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=42)

In [ ]:
x_train

    Area Sq Ft  Bedrooms  Bathrooms  House Age Years  Distance to City Km
55        2893         3          4               27                 22.3
88        2205         3          1               29                  1.4
26        2458         1          3                1                 22.7
42        1280         1          4               25                  7.4
69         647         5          4                9                  6.8
..         ...       ...        ...              ...                  ...
60        2594         3          4               31                 17.1
71        1180         2          4                7                  5.1
14        1743         5          3                6                 23.0
92        1451         3          1               29                 13.7
51        2233         1          2               12                  7.1

[80 rows x 5 columns]

In [ ]:
y_train

55    354478.01
88    280370.27
26    304499.62
42    174484.01
69    162237.69
        ...
60    336719.54
71    195398.92
14    250978.63
92    183540.84
51    289940.27
Name: House Price, Length: 80, dtype: float64

In [ ]:
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [ ]:
model.intercept_

np.float64(30057.71070315133)

In [ ]:
model.coef_

array([  114.16219059,  9307.14637026,  7761.36659314,  -981.13642171,
       -1705.70256966])

In [ ]:
y_train_predicted=model.predict(x_train)
y_train_predicted

array([354767.98287763, 286627.20683374, 303559.03657345, 179387.31784458,
       161072.84097052,  56732.33100225, 226465.25312839, 149531.73606765,
       172975.25817994, 325064.62378527, 171344.28268612, 171704.98153095,
       303705.12624464, 132049.36877496, 296502.0062697 , 326591.33615911,
       203747.58745809, 240177.01046919, 140140.93736733, 359279.32073747,
       292387.9176601 , 253776.01529426, 301229.28248549,  93524.70438027,
       297059.94281836, 364496.86018867, 184083.30872527, 150445.26499633,
       284437.96768178, 308520.33383424, 321146.89457328, 214994.24572573,
       212047.55614786, 115251.80594095, 313390.81090561, 238145.8993203 ,
        85083.44226121, 135886.36562787,  87036.82476199, 349863.70444961,
       232607.42021975, 254732.25553295, 233340.58492758, 348964.43496896,
        42077.34192272, 191708.70110946, 293802.10568897, 296382.81194352,
       289367.89911467, 365403.40014162,  91923.15013414, 135575.4880013 ,
       143302.91844746, 298593.01750994, 173402.2403728 , 227792.65569059,
       203830.09327952, 344177.81410764, 241454.72698663, 356205.282887  ,
       181169.62791732, 180606.04434419,  78036.78091709, 140963.67665428,
       307491.51904305, 266665.60687386, 138187.0032925 , 237073.11714772,
       300648.26181887, 307956.1145851 , 407025.42789486, 200545.44531719,
       292625.74816499, 119514.77452068, 344579.67058963, 325578.59556617,
       198861.81665677, 253744.26290221, 179568.77352111, 285927.63654503])

In [ ]:
y_test_predicted=model.predict(x_test)
y_test_predicted

array([220303.47657454, 168338.13666306,  64294.26015255, 373681.36517708,
       232644.67849227, 178230.94796407, 362446.47484072, 264517.75719406,
       226124.33767478, 204192.82022082, 243574.61674293, 145316.74419135,
       301540.48947507, 324801.91447688, 302828.08797214, 303017.42774739,
       211201.04467219, 114958.33163418, 214135.7767219 , 188596.66598667])

In [ ]:
# r2 score

r2_train_score=r2_score(y_train,y_train_predicted)
r2_train_score

0.9963897042629054

1. Conclusion for Training R² Score

The training R² score is 0.9964, indicating that the model explains approximately 99.64% of the variance in the training data. This suggests that the model fits the training data very well.

In [ ]:

r2_test_score=r2_score(y_test,y_test_predicted)
r2_test_score

0.993422344935731

2. Conclusion for Testing R² Score

The testing R² score is 0.9934, indicating that the model explains approximately 99.34% of the variance in the testing data. This suggests that the model performs very well on unseen data.

In [ ]:
# mse

mse_train_score=mean_squared_error(y_train,y_train_predicted)
mse_train_score

27093604.992749006


3. Conclusion for Training MSE

The training Mean Squared Error (MSE) is 27,093,604.99, representing the average squared difference between the actual and predicted training values. A lower MSE indicates better prediction accuracy.

In [ ]:
mse_test_score=mean_squared_error(y_test,y_test_predicted)
mse_test_score

41808058.45465721

4. Conclusion for Testing MSE

The testing Mean Squared Error (MSE) is 41,808,058.45, which is higher than the training MSE. This indicates that the model makes slightly larger prediction errors on unseen data.

In [ ]:
# mae
mae_train_score=mean_absolute_error(y_train,y_train_predicted)
mae_train_score

4126.614367657423

5.Conclusion for Training MAE

The training Mean Absolute Error (MAE) is 4126.61, indicating that the model's predictions differ from the actual training values by approximately 4126.61 units on average.

In [ ]:
mae_test_score=mean_absolute_error(y_test,y_test_predicted)
mae_test_score

5210.275236200138

5.Conclusion for Testing MAE
 
 The testing Mean Absolute Error (MAE) is 5210.28, indicating that the model's predictions differ from the actual testing values by approximately 5210.28 units on average.

In [ ]:
# rmse
rmse_train_score=root_mean_squared_error(y_train,y_train_predicted)
rmse_train_score

5205.15177422801


6. Conclusion for Training RMSE

The training Root Mean Squared Error (RMSE) is 5205.15, representing the typical prediction error in the training data, with greater emphasis on larger errors.

In [ ]:
rmse_test_score=root_mean_squared_error(y_test,y_test_predicted)
rmse_test_score

6465.915128940157


7.Conclusion for Testing RMSE

The testing Root Mean Squared Error (RMSE) is 6465.92, which is higher than the training RMSE. This indicates that the model makes somewhat larger prediction errors on unseen data.